project_name: scpw

builds:
  - binary: scpw

    main: ./cmd/scpw/main.go
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.Build={{.Version}}

    goos:
      - darwin
      - linux
      - freebsd
      - windows
    goarch:
      - amd64
      - arm64
      - mips64
      - mips64le
    goarm:
      - 7
      - 6
      - 5
    gomips:
      - hardfloat
      - softfloat

    ignore:
      - goos: freebsd
        goarch: mips64
      - goos: freebsd
        goarch: arm64
      - goos: freebsd
        goarch: amd64

archives:
  - id: scpw
    name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
