name: SCPW Test Coveralls
run-name: ${{ github.actor }} is Coveralls GitHub Actions 🚀
on: [ "push", "pull_request" ]
jobs:
  SCPW-Test-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: "1.19"
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          go mod download
      - name: Prepare test-case
        run: |
          chmod +x ${{ github.workspace }}/.github/script/test/prepare.sh
          sh ${{ github.workspace }}/.github/script/test/prepare.sh
      - name: Run Unit Tests
        run: |
          go test -tags noasm -race -covermode atomic -coverprofile=profile.cov ./...
          go test -race ./...
      - name: Upload Coverage
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: profile.cov
